// <auto-generated />
using TwitterStatsBlazorApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TwitterStatsBlazorApp.Server.Migrations
{
    [DbContext(typeof(TwitterStatsContext))]
    partial class TwitterStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlazorApp1.Shared.TwitterStat", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("TwitterStats");

                    b.HasData(
                        new
                        {
                            Key = "TotalNumberOfTweets",
                            Value = "0"
                        },
                        new
                        {
                            Key = "AverageTweetsPerHour",
                            Value = "0"
                        },
                        new
                        {
                            Key = "AverageTweetsPerMinute",
                            Value = "0"
                        },
                        new
                        {
                            Key = "AverageTweetsPerSecond",
                            Value = "0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
